"use client";
import { useState, useTransition } from "react";
import { saveLanding } from "./actions";
import type { LandingConfig } from "./schema";

const labels: Record<string, string> = { eyebrow: "Chamada inicial", title: "Título principal", subtitle: "Proposta de valor", cta_label: "Texto do botão", cta_url: "Destino da contratação (mantenha /#planos até configurar o checkout)", pain_title: "Título do problema", pain_description: "Descrição do problema", benefits_title: "Título dos benefícios", steps_title: "Título do passo a passo", pricing_title: "Título dos planos", pricing_note: "Condições comerciais", closing_title: "Título final", closing_description: "Mensagem final" };
const inputClass = "mt-1 w-full rounded-md border bg-background p-2 text-foreground";
export function SettingsForm({ initial }: { initial: LandingConfig }) {
  const [config, setConfig] = useState(initial);
  const [status, setStatus] = useState("");
  const [pending, start] = useTransition();
  function field(label: string, value: string, change: (value: string) => void, multiline = false) {
    return <label className="block text-sm" key={label}>{label}{multiline ? <textarea className={inputClass} value={value} maxLength={3000} rows={3} onChange={e => change(e.target.value)} /> : <input className={inputClass} value={value} maxLength={1000} onChange={e => change(e.target.value)} />}</label>;
  }
  function updateCreditPack(index: number, patch: Partial<LandingConfig["credit_packs"][number]>) {
    setConfig({ ...config, credit_packs: config.credit_packs.map((pack, current) => current === index ? { ...pack, ...patch } : pack) });
  }
  return <form className="max-w-4xl space-y-6" onSubmit={e => { e.preventDefault(); start(async () => { try { const result = await saveLanding(config); setStatus(result.error ?? "Página publicada com as alterações salvas."); } catch { setStatus("Não foi possível salvar. Confira sua sessão e tente novamente."); } }); }}>
    <p className="rounded-lg border p-4 text-sm">Esta página é pública e única para a instalação. Ao salvar, os próximos checkouts mensais da Stripe usam os novos preços; sessões já abertas preservam o valor apresentado ao cliente.</p>
    <fieldset disabled={pending} className="space-y-5 rounded-lg border p-5"><legend>Aparência e conteúdo</legend>
      <label className="block text-sm">Tema<select className={inputClass} value={config.theme} onChange={e => setConfig({ ...config, theme: e.target.value as LandingConfig["theme"] })}><option value="dark">Escuro</option><option value="light">Claro</option></select></label>
      <label className="block text-sm">Cor de destaque<input type="color" value={config.accent} onChange={e => setConfig({ ...config, accent: e.target.value })} className="ml-3" /></label>
      {Object.entries(labels).map(([key, label]) => field(label, config[key as keyof LandingConfig] as string, value => setConfig({ ...config, [key]: value }), key.includes("description") || key === "subtitle"))}
    </fieldset>
    {(["benefits", "steps"] as const).map(kind => <fieldset disabled={pending} className="space-y-4 rounded-lg border p-5" key={kind}><legend>{kind === "benefits" ? "Cards de benefícios" : "Passo a passo"}</legend>{config[kind].map((card, index) => <div className="grid gap-3 border-b pb-4 md:grid-cols-2" key={index}>{field(`Título ${index + 1}`, card.title, value => setConfig({ ...config, [kind]: config[kind].map((c, i) => i === index ? { ...c, title: value } : c) }))}{field(`Descrição ${index + 1}`, card.description, value => setConfig({ ...config, [kind]: config[kind].map((c, i) => i === index ? { ...c, description: value } : c) }), true)}</div>)}</fieldset>)}
    <fieldset disabled={pending} className="space-y-5 rounded-lg border p-5"><legend>Planos, cotas e cobrança mensal</legend>{config.plans.map((plan, index) => <div className="space-y-3 border-b pb-4" key={plan.slug}>{field(`${index + 1} · Nome`, plan.name, value => setConfig({ ...config, plans: config.plans.map((p, i) => i === index ? { ...p, name: value } : p) }))}<label className="block text-sm">{index + 1} · Valor mensal (R$)<input className={inputClass} type="number" min="1" step="0.01" value={(plan.price_cents / 100).toFixed(2)} onChange={e => setConfig({ ...config, plans: config.plans.map((p, i) => i === index ? { ...p, price_cents: Math.round(Number(e.target.value) * 100) } : p) })} /></label><div className="grid gap-3 md:grid-cols-2">{([['users','Usuários'],['whatsapp','WhatsApps'],['active_agents','Agentes ativos'],['monthly_conversations','Conversas automatizadas/mês']] as const).map(([key,label]) => <label className="block text-sm" key={key}>{label}<input className={inputClass} type="number" min="1" value={plan.limits[key]} onChange={e => setConfig({ ...config, plans: config.plans.map((p,i) => i===index ? { ...p, limits: { ...p.limits, [key]: Math.max(1,Math.floor(Number(e.target.value)||1)) } } : p) })} /></label>)}</div>{field(`${index + 1} · Descrição`, plan.description, value => setConfig({ ...config, plans: config.plans.map((p, i) => i === index ? { ...p, description: value } : p) }))}{field(`${index + 1} · Recursos (um por linha)`, plan.features.join("\n"), value => setConfig({ ...config, plans: config.plans.map((p, i) => i === index ? { ...p, features: value.split("\n").filter(Boolean) } : p) }), true)}</div>)}</fieldset>
    <fieldset disabled={pending} className="space-y-4 rounded-lg border p-5"><legend>Adicionais e cobrança mensal</legend><p className="text-sm text-muted-foreground">Os valores abaixo aparecem no checkout da organização ativa. Desativar impede novas compras, sem retirar capacidade já contratada.</p>{config.addons.map((addon, index) => <div className="grid gap-3 border-b pb-4 md:grid-cols-4" key={addon.slug}>{field(addon.name, addon.name, value => setConfig({ ...config, addons: config.addons.map((a,i)=>i===index?{...a,name:value}:a) }))}<label className="block text-sm">Unidades<input className={inputClass} type="number" min="1" value={addon.units} onChange={e => setConfig({ ...config, addons: config.addons.map((a,i)=>i===index?{...a,units:Math.max(1,Math.floor(Number(e.target.value)||1))}:a) })} /></label><label className="block text-sm">Valor mensal (R$)<input className={inputClass} type="number" min="1" step="0.01" value={(addon.price_cents/100).toFixed(2)} onChange={e => setConfig({ ...config, addons: config.addons.map((a,i)=>i===index?{...a,price_cents:Math.round(Number(e.target.value)*100)}:a) })} /></label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={addon.active} onChange={e=>setConfig({ ...config, addons: config.addons.map((a,i)=>i===index?{...a,active:e.target.checked}:a) })} />Disponível</label></div>)}</fieldset>
    <fieldset disabled={pending} className="space-y-4 rounded-lg border p-5"><legend>Política comercial e consumo</legend>
      <p className="text-sm text-muted-foreground">Zero desativa teste, desconto anual ou cobrança excedente. A cobrança por resultado fica indisponível enquanto não houver um valor definido.</p>
      <div className="grid gap-3 md:grid-cols-3">
        <label className="block text-sm">Desconto anual (%)<input className={inputClass} type="number" min="0" max="40" value={config.billing.annual_discount_percent} onChange={e=>setConfig({...config,billing:{...config.billing,annual_discount_percent:Math.max(0,Math.min(40,Math.floor(Number(e.target.value)||0)))}})} /></label>
        <label className="block text-sm">Teste gratuito (dias)<input className={inputClass} type="number" min="0" max="30" value={config.billing.trial_days} onChange={e=>setConfig({...config,billing:{...config.billing,trial_days:Math.max(0,Math.min(30,Math.floor(Number(e.target.value)||0)))}})} /></label>
        <label className="block text-sm">Aviso de consumo (%)<input className={inputClass} type="number" min="50" max="99" value={config.billing.usage_alert_percent} onChange={e=>setConfig({...config,billing:{...config.billing,usage_alert_percent:Math.max(50,Math.min(99,Math.floor(Number(e.target.value)||80)))}})} /></label>
        <label className="block text-sm">Teto operacional (%)<input className={inputClass} type="number" min="100" max="200" value={config.billing.hard_limit_percent} onChange={e=>setConfig({...config,billing:{...config.billing,hard_limit_percent:Math.max(100,Math.min(200,Math.floor(Number(e.target.value)||100)))}})} /></label>
        <label className="block text-sm">Excedente por 1.000 respostas (R$)<input className={inputClass} type="number" min="0" step="0.01" value={(config.billing.overage_unit_price_cents/100).toFixed(2)} onChange={e=>setConfig({...config,billing:{...config.billing,overage_unit_price_cents:Math.max(0,Math.round(Number(e.target.value)*100)||0)}})} /></label>
        <label className="block text-sm">Valor por resultado da IA (R$)<input className={inputClass} type="number" min="0" step="0.01" value={(config.billing.outcome_price_cents/100).toFixed(2)} onChange={e=>setConfig({...config,billing:{...config.billing,outcome_price_cents:Math.max(0,Math.round(Number(e.target.value)*100)||0)}})} /></label>
      </div>
      <label className="flex gap-2 text-sm"><input type="checkbox" checked={config.billing.outcome_billing_enabled} onChange={e=>setConfig({...config,billing:{...config.billing,outcome_billing_enabled:e.target.checked}})} />Oferecer cobrança por resultado entregue pela IA</label>
      {field("Aviso sobre tarifas oficiais do WhatsApp/Meta", config.billing.meta_fees_notice, value=>setConfig({...config,billing:{...config.billing,meta_fees_notice:value}}), true)}
    </fieldset>
    <fieldset disabled={pending} className="space-y-4 rounded-lg border p-5"><legend>Créditos pré-pagos de IA</legend><p className="text-sm text-muted-foreground">Créditos são compra única, não expiram e só são consumidos depois da franquia mensal.</p>{config.credit_packs.map((pack,index)=><div className="grid gap-3 border-b pb-4 md:grid-cols-4" key={pack.slug}>
      {field(pack.name, pack.name, value => updateCreditPack(index, { name: value }))}
      <label className="block text-sm">Créditos<input className={inputClass} type="number" min="1000" step="1000" value={pack.units} onChange={e => updateCreditPack(index, { units: Math.max(1000, Math.floor(Number(e.target.value) || 1000)) })} /></label>
      <label className="block text-sm">Compra única (R$)<input className={inputClass} type="number" min="1" step="0.01" value={(pack.price_cents/100).toFixed(2)} onChange={e => updateCreditPack(index, { price_cents: Math.max(100, Math.round(Number(e.target.value) * 100) || 100) })} /></label>
      <label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={pack.active} onChange={e => updateCreditPack(index, { active: e.target.checked })} />Disponível</label>
    </div>)}</fieldset>
    <fieldset disabled={pending} className="space-y-4 rounded-lg border p-5"><legend>Perguntas frequentes</legend>{config.faq.map((item, index) => <div key={index}>{field(`Pergunta ${index + 1}`, item.question, value => setConfig({ ...config, faq: config.faq.map((q, i) => i === index ? { ...q, question: value } : q) }))}{field(`Resposta ${index + 1}`, item.answer, value => setConfig({ ...config, faq: config.faq.map((q, i) => i === index ? { ...q, answer: value } : q) }), true)}</div>)}</fieldset>
    <div className="sticky bottom-0 flex flex-wrap items-center gap-4 border-t bg-background p-4"><button disabled={pending} className="rounded-md bg-primary px-5 py-2 text-primary-foreground">{pending ? "Salvando…" : "Salvar e publicar"}</button><a href="/" target="_blank" rel="noopener noreferrer" className="underline">Ver página pública ↗</a><p role="status" className="text-sm">{status}</p></div>
  </form>;
}
